client/templates/home/home.html

center header and align social icon

---

client/templates/calendar/calendarEvent.html
client/templates/map/map.js

Hidden overlapping text on small screens, moved address line for better display

Event list page

---

client/templates/map/map.js

Initial zoom changed, grey area when dragging fixed, min zoom changed.

mapZoom and grey area

---

.meteor/packages
.meteor/versions
client/stylesheets/calendar/calendar.css
client/templates/calendar/calendarEvent.html
server/seeds/events.js

Hidden overlapping text on small screens, moved address line

Eventslist

---

client/stylesheets/calendar/calendar.css
client/templates/calendar/calendar.html
client/templates/calendar/calendar.js

This is an address filter for events in the list view (issue #24).

Country city search

---

client/templates/map/map.js

This fixes events not showing up in map (issue #62 ). Also, updated the geocoder package.

Events not showing bug fix

---

client/templates/eventsForm/eventsForm.js
client/templates/map/map.js

This should fix issue #62 . Events are now showing on the map and being added to the map after creating them.

Fixed bug - events not showing after leaving the map and comming back

---

both/collections/events.js
client/helpers/stringHelpers.js

Fixed missing part of issue #6.

Small time fix

---

client/templates/map/popup/eventPopup.js

Fixes one of the problems in issue #69

Fixed show more btn not working after changing view

---

client/templates/congratsModal/congratsModal.html
client/templates/map/map.js

@AndyatFocallocal I would argue that this is more of a patch, maybe it can be improved later after the Beta release. (issue #69)

Added auto-reload after creating an event

---

both/collections/events.js
client/templates/event/eventAbout/cards/infoCard.html
client/templates/map/popup/eventPopup.html

Fixes issue #33 
Added an overview field to the events collection. Updated character limit for the event's description.
- Description: 400 characters
- Overview: 150 characters

Added overview field to events

---

client/helpers/stringHelpers.js

Removed timezone convertions from string helpers

---

both/collections/events.js
client/stylesheets/eventForm/slidepanel.scss
client/templates/eventsForm/eventsForm.js

Added character counter to new event form

---

.meteor/versions
client/templates/eventsForm/new/newEvent.html
client/templates/eventsForm/new/newEvent.js
client/templates/eventsForm/sequenceForm.js

Added Validation and updated a few packages issue #86

Refactor new event form

---

client/stylesheets/map/map.css
client/templates/eventsForm/commun.js
client/templates/eventsForm/edit/editEvent.html
client/templates/eventsForm/edit/editEvent.js
client/templates/eventsForm/new/newEvent.js
client/templates/map/map.html
client/templates/map/map.js
client/templates/map/popup/eventPopup.js

Should complete implementation of google maps
Fixes issues #93, #5, and possibly issue #84

Change to google maps

---

client/templates/map/map.js
package.json

I have added the option to can select were to put the controls on the map. Just go inside map.js and change the options if you want to do it.

Resolved conflict with map CONTROLS

---

client/stylesheets/map/map.css
client/templates/map/map.js

Fixed search bar

---

client/templates/map/map.js

changes styles as wanted and added the posibility to style it however you want.

changed styles to map

---

.meteor/packages
.meteor/versions
both/i18n/en/app.en.i18n.json
client/templates/home/home.html
client/templates/home/home.js

i have added the i18n package and provided an simple example on how to use it. Now Andy should just create an .json object with all the changes that he wants using my code as an example, and paste it to the slack channel so a dev can paste it inside of the project and replace all keys in code.

added i18n, the package takes some time to install

---

both/i18n/en/app.en.i18n.json
client/templates/congratsModal/congratsModal.html
client/templates/eventsForm/edit/editEvent.html
client/templates/eventsForm/new/newEvent.html
client/templates/home/home.html
client/templates/map/eventConfirmDelete/eventConfirmDelete.html

Enabled some of the text. (still not editable through the ui)

Text i18n enable

---

client/templates/event/event.html
client/templates/eventConfirmReport/eventConfirmReport.html
client/templates/eventConfirmReport/eventConfirmReport.js
client/templates/map/map.html
client/templates/map/map.js
client/templates/map/popup/eventPopup.html

@AndyatFocallocal These are the small fixes you requested

General bug fixes

---

both/router/routes.js
client/stylesheets/godmode/godmode.scss
client/stylesheets/index.scss
client/templates/godmode/godmode.html
client/templates/godmode/godmode.js
client/templates/map/map.js
server/methods/admin.js
server/seeds/accounts.js

@AndyatFocallocal This adds the core for /godmode. It's not full featured, but It allows for enabling and disabling admins.

Admin godmode

---

.travis.yml

No way to look at travis env vars through the UI. I'll change the encryption keys after taking a look at the variables.

COMMIT NOT SECURE --- echo's travis env variables

---

.gitattributes
.travis.yml

Adds the street sleeper branch to the travis build process

Sleeper travis

---

both/i18n/en/app.en.i18n.json
client/stylesheets/materialize/components/_waves.scss
client/templates/home/home.html
client/templates/layouts/headerMenu/leftLinks.html

edited menu icons and paragraph width

commitedfiles2

---

client/templates/eventsForm/new/newEvent.js

This reverts commit c2884fb4222195f33703f5f3aab10efb493eb577, reversing
changes made to 8ff1a4370a6979bb1076beb417244d2eed601fe9.

Revert "Merge pull request #198 from ydaniel98/new-resource-btn"

---

client/stylesheets/map/map.css
client/templates/map/map.js

[print-beta-1.pdf](https://github.com/focallocal/fl-maps/files/1163158/print-beta-1.pdf)
For issue #35

Added ability to print maps

---

both/collections/events.js
client/templates/eventsForm/lifetime/lifetime.html
client/templates/eventsForm/lifetime/lifetime.js

Reverts focallocal/fl-maps#367

Revert "Street sleeper"

---

both/i18n/en/app.en.i18n.json
client/templates/eventsForm/new/newEvent.html
client/templates/layouts/headerMenu/_header.html
client/templates/layouts/headerMenu/sideNav/sideNavLinks.html
client/templates/sequenceForm/sequenceForm.js

The activities link was not included correctly.
It's working on both the header menu and the sidebar
This PR also fix:
#526 
#520

small bug fixes

---

client/stylesheets/congratsModal/index.scss
client/templates/congratsModal/congratsModal.html

applied spacing in "selectable" div

---

client/stylesheets/map/map.css
client/templates/map/map.html

small fixes

---

imports/both/i18n/en/home.json
imports/client/ui/components/Logos/FriendsLogo/FriendsLogo.js
imports/client/ui/components/Logos/FriendsLogo/styles.scss
imports/client/ui/components/Logos/ShareLogo/ShareLogo.js
imports/client/ui/components/Logos/ShareLogo/styles.scss
imports/client/ui/components/Logos/SmileyLogo/Smileylogo.js
imports/client/ui/components/Logos/SmileyLogo/styles.scss
imports/client/ui/pages/Home/SecondSection/About/Logos/FriendsLogo/FriendsLogo.js
imports/client/ui/pages/Home/SecondSection/About/Logos/FriendsLogo/styles.scss
imports/client/ui/pages/Home/SecondSection/About/Logos/ShareLogo/ShareLogo.js
imports/client/ui/pages/Home/SecondSection/About/Logos/ShareLogo/styles.scss
imports/client/ui/pages/Home/SecondSection/About/Logos/SmileyLogo/Smileylogo.js
imports/client/ui/pages/Home/SecondSection/About/Logos/SmileyLogo/styles.scss
imports/client/ui/pages/Home/SecondSection/About/index.js
imports/client/ui/pages/Home/SecondSection/About/styles.scss
imports/client/ui/pages/Home/SecondSection/index.js
imports/client/ui/pages/Home/SecondSection/styles.scss
imports/client/ui/pages/Home/__tests__/Home.test.js
imports/client/ui/pages/Home/__tests__/SecondSection.test.js
imports/client/ui/pages/Home/index.js

Homepage:
- Second section.
- Test suite.

React maps

---

imports/client/ui/components/NewEventModal/CongratsModal/index.js
imports/client/ui/pages/Map/EventInfo/index.js
imports/client/ui/pages/Map/NewEvent/index.js
imports/client/ui/pages/Map/index.js
imports/client/utils/format.js

Google maps

---

imports/both/collections/events/DaysSchema.js
imports/both/collections/events/SpecificPeriodSchema.js
imports/client/ui/components/NewEventModal/CongratsModal/index.js
imports/client/ui/components/NewEventModal/FormWizard/index.js
imports/client/ui/pages/Map/EventInfo/index.js
imports/client/ui/pages/Map/EventInfo/styles.scss
imports/client/ui/pages/Map/NewEvent/index.js
imports/client/ui/pages/Map/index.js

Small changes

---

imports/both/i18n/en/home.json
imports/client/ui/pages/Home/FifthSection/MoreLinks/Option/index.js
imports/client/ui/pages/Home/FifthSection/MoreLinks/Option/styles.scss
imports/client/ui/pages/Home/FifthSection/MoreLinks/index.js
imports/client/ui/pages/Home/FifthSection/MoreLinks/styles.scss
imports/client/ui/pages/Home/FifthSection/index.js
imports/client/ui/pages/Home/FifthSection/styles.scss
imports/client/ui/pages/Home/__tests__/FifthSection.test.js
imports/client/ui/pages/Home/__tests__/Home.test.js
imports/client/ui/pages/Home/index.js
package-lock.json

Added fifth-section.
- CSS needs improvement.

Home fifth section

---

imports/client/ui/pages/Map/EventInfo/index.js

Made requested changes per: 
https://github.com/focallocal/fl-maps/issues/585

Changed: Looks Suspicious to Report Issue, per #585

---

imports/client/ui/pages/Home/HowToHelpSection/index.js
imports/client/ui/pages/Home/index.js

Adjusted sign-in and post button to open event creation form and logic for logged in.

Adjusted sign in and post button

---

imports/both/collections/events/index.js
imports/both/i18n/en/categories.json
imports/both/i18n/en/new-event-modal.json
imports/client/ui/pages/Home/index.js
imports/client/ui/pages/NewEvent/CongratsModal/index.js
imports/client/ui/pages/NewEvent/FormWizard/FirstStep.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/ui/pages/NewEvent/FormWizard/index.js
imports/client/ui/pages/NewEvent/styles.scss
imports/client/utils/uniforms-custom/AutoForm.js
imports/client/utils/uniforms-custom/SelectField.js

- Updated the categories selection to properly assign Community Resource when Radio Selected.
- Congrats/Thank you Done button directs to newly created pages vs Maps
- New Event Modal layout updated to wire frame order

Modal update

---

imports/both/i18n/en/categories.json

I have removed the excess categories  from the stated in this issue post https://github.com/focallocal/fl-maps/issues/634

removed washing clothes and support group categories

---

imports/client/stylesheets/variables.scss
imports/client/ui/includes/MainMenu/index.js
imports/client/ui/includes/MainMenu/styles.scss
imports/client/ui/pages/Home/styles.scss

Swapped  the render order of the logo and the burger menu, no need to add an additional div and flex to it that caused additional issues, changed the flex to 15 on the burger menu.

Menu logo issue

---

imports/client/ui/app.js

Fixed a problem with the blank page on https://focallocal.org/home with help from @ydaniel98 .

fixed the blank page on "/home" by redirecting to "/" route

---

imports/client/ui/app.js
imports/client/ui/pages/HackDay/index.js

I have added the hackday page and it is available at /hackday route
Currently there is a conflict in the styles as shown in the screenshot above.

Hack day Page

---

imports/client/ui/app.js
imports/client/ui/pages/HackDay/index.js

Reverts focallocal/fl-maps#698
created a menu issue

Revert "Hack day Page"

---

imports/client/ui/pages/Home/HowToHelpSection/index.js

Added text to the main page #715

added text to main page

---

imports/client/utils/uniforms-custom/DateField.js

Both: Added dropdown menus to date picker for easier navigation

---

imports/client/utils/uniforms-custom/DateField.js

The previous comment on PR #720 has a snapshot of the line where the value isn't being set.

Fixed values not being set by date picker.

---

imports/client/ui/pages/Home/HowToHelpSection/index.js

Reverts focallocal/fl-maps#722

Revert "Fixed add-text Merge Conflict"

---

.travis.yml

Just testing Travis CI  build process.

Changed a line to test a PR on focallocal repo

---

imports/both/i18n/en/home.json

Testing PR build for this branch, don't panic and bring a towel

---

.travis.yml

Another test, this time adding this branch to the safelist to build

---

.travis.yml

fix for certificate issue.
Removed safe list for branch, dont expect Travis CI to build this branch.

removing safe list for this branch

---

.travis.yml
_config.yml

- Updated Travis CI Script
- Issues before were other branches kicking off a new build and publishing to the server. Now it only builds correctly if it's **Master** or **fl-sleeper**
- Added Job steps
- Currently, the Init stage is where we install our project dependencies. Right now we have on install_before
- We have to get back into the habit to start Unit Testing with jest which I added a Job Step into the file.
- The last one is a deploy step which deploys the correct environment
- Future Feature: Add notifications to his build step which updates developers and on Slack

Updated travis script

---

.travis.yml
_config.yml

Reverts focallocal/fl-maps#754

Revert "Updated travis script"

---

imports/client/ui/app.js
imports/client/ui/pages/NewEvent/FormWizard/index.js
imports/client/ui/pages/NewEvent/index.js

Same changes in New Event Modal as in #772, but branched out from new-fl-sleeper instead of new-master.

Same as #772, but against new-fl-sleeper

---

imports/both/i18n/en/map.json
imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss

Changed About and about section to Introduction and intro section in Page review in the Map.
The 'Introduction' title was added to i18n as 'introTitle' in map.json
Introduction and Meet Me sections were added to Event detail page.

Pull request to fix issue #778

---

imports/both/collections/events/index.js
imports/both/i18n/en/new-event-modal.json
imports/client/ui/pages/NewEvent/FormWizard/FirstStep.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/ui/pages/NewEvent/FormWizard/index.js
imports/client/ui/pages/NewEvent/index.js
imports/client/ui/pages/NewEvent/styles.scss

Addressed #757 
Alert appears if 'Put myself on the Map!' radio button is selected 
Adressed #679 
Added radio buttons in Second Step (third and fourth radio button) of New Event modal to i18n new-event-modal.json 
Moved date and time input fields closer together 
Addressed #721 
Attendee limit added to i18n new-event-modal.json 
Changed Error Alert text (when form errors appear after submit). 
Changed Modal body css and other small things. 
'reset fields' line was replaced with a Button.

Pull request for issues #757, #679, #721 

---

imports/both/collections/events/index.js
imports/both/i18n/en/new-event-modal.json
imports/client/ui/pages/NewEvent/FormWizard/FirstStep.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/ui/pages/NewEvent/FormWizard/index.js
imports/client/ui/pages/NewEvent/index.js
imports/client/ui/pages/NewEvent/styles.scss

Same as pull request #779, but for new-fl-sleeper

Pull request for issues #757, #679, #721 for new-fl-sleeper 

---

imports/client/ui/style.scss

See https://github.com/sylque/dcs-discourse-plugin/issues/3

Fix attempt for hidden reply button on mobile

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Map/EventsList/index.js
imports/client/ui/pages/Map/index.js

Swapped out Get Directions button for Attending button in EventInfo component. Only signed-in users can Attend, otherwise they are redirected to auth page (same component/same behavior as Attending button in Page component)

Changed Get Directions to Attending button, #767

---

README.md

Hi Andy,
Please find my pull request with README.md to include the Step (5) Warnings section when running meteor npm install twice and the collapsible detaiiled description information.
Best regards,
Kean (kso)

explicitly stated to run meteor npm install once

---

imports/both/i18n/en/menu.json
imports/client/ui/includes/MainMenu/Sidebar/index.js
imports/client/ui/includes/MainMenu/Sidebar/styles.scss
imports/client/ui/includes/MainMenu/UserItem/index.js
imports/client/ui/includes/MainMenu/index.js
package-lock.json

Moved "`home`" to the top of `leftLinks` in `menu.json`. Added `loginRequired` property to menu items. Added logic to render only "`home`" and "`about us`" links in `MainMenu` and `Sidebar`, when user is not logged in. Changed Sidebar's flex-direction from `column-reverse`  to `column`. Wrapped `MainMenu` in `withTracker` and passed down `user` prop to `UserItem`.  
#798

Fixed issue #798. 

---

imports/both/i18n/en/team.json

- Added myself to the team
- Fixed some indentation

Add matias to team

---

imports/both/i18n/en/map.json
imports/both/i18n/en/new-event-modal.json

Starting to fix i18n issues. Might be more, my local env is broken and it's hard to test.

Fix i18n issues

---

imports/client/ui/pages/Map/EventsFilter/index.js
imports/client/ui/pages/Map/index.js

This is the same as https://github.com/focallocal/fl-maps/pull/842 fixing #820 - but targeting only the fl-sleeper branch.

New PR to fix events on map for fl-sleeper branch only

---

imports/both/i18n/en/team.json

I added myself to the team members. It's been 4 years and this project is still rocking! Great job!

Adds Pawel to the team

---

imports/client/ui/pages/NewEvent/FormWizard/FirstStep.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js

Increased max chars for Intro and Description on New Event Form

---

imports/client/stylesheets/variables.scss
imports/client/ui/pages/Page/Edit/styles.scss
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss

Fl-sleeper switched attend and edit buttons

---

imports/client/stylesheets/variables.scss
imports/client/ui/pages/Page/Edit/styles.scss
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss

Reverts focallocal/fl-maps#858

Revert "Fl-sleeper switched attend and edit buttons"

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Page/AttendingButton/index.js
imports/client/ui/pages/Page/index.js

replica of [this PR on the master branch](https://github.com/focallocal/fl-maps/pull/877)
removed Attend button UI

Removed attending button (equivalent to PR #877 on master branch)

---

imports/client/ui/pages/Home/FirstSection/Find/index.js
imports/client/utils/location/getUserPosition.js

OK this is how I think I need to do it. The same as the changes I made for master.

Users typing a location to search manually, doesn't work" fixed #872

---

imports/both/collections/events/index.js
imports/client/ui/pages/Map/SearchButtons/index.js
imports/client/ui/pages/Map/index.js
server/methods/events/getFutureEvents.js
server/methods/events/index.js

Relates to https://github.com/focallocal/fl-maps/pull/886

past events filter - merging changes from master to fl-sleeper (#886)

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Map/EventsList/EventInfo/styles.scss
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss
package.json

Replica of [this fix in master branch](https://github.com/focallocal/fl-maps/commit/fa3b2bb37a4a45700842b1d9e29f7d3bbd8f9b78)

Fix URL and long words: equivalent to PR 894 from Master

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

Merging across [PR 896](https://github.com/focallocal/fl-maps/pull/896) to fl-sleeper.
Relates to [issue 879](https://github.com/focallocal/fl-maps/issues/879)

merge PR #896 from master to fl-sleeper (weekly repeating event bug fix)

---

imports/both/i18n/en/team.json

As discussed, added my details on the team page json (let me know if this was the wrong place to edit). Cheers!

revised i18n team page

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

Second attempt at [this PR](https://github.com/focallocal/fl-maps/pull/896).
For reference: original was manually reverted due to unknown Travis build failure(s).

retrying PR896 (bugfix-weekday-default)

---

imports/client/ui/pages/Home/HowToHelpSection/Item/index.js
imports/client/ui/pages/Home/HowToHelpSection/index.js
imports/client/ui/pages/Home/HowToHelpSection/styles.scss

Copied code from #848 into master.

fix: re-add-join-button

---

imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/components/HoursFormatted/styles.scss
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/Monthly/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js
imports/client/utils/findNextEvent.js

equivalent to [PR 909 on master](https://github.com/focallocal/fl-maps/pull/909)

(fl-sleeper) Events recurrence - complete timeDate module and repair recurrence selection

---

imports/client/ui/components/HoursFormatted/index.js

Delete quick fix

---

imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

Equivalent to [this PR913 on master](https://github.com/focallocal/fl-maps/pull/913/commits/0c863e15ed271932a370fa5c26dbca7a45a14187)

Bugfix: Attempting to edit event to recur breaks the app (fl-sleeper)

---

imports/client/ui/pages/Partners/Members.js

Switch Partners component to use partners data

---

imports/client/ui/pages/Partners/Members.js

[Fl-sleeper] Switch Partners component to use Partners data

---

imports/client/ui/includes/MainMenu/Logo/index.js
imports/client/ui/includes/MainMenu/Logo/styles.scss
webpack.config.js

Fixed color of logo on mobile.

fix logo on mobile

---

imports/client/ui/includes/MainMenu/Logo/index.js

fix: change btmImgUrl to imgUrl

---

imports/both/collections/events/helpers/index.js
imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/utils/format.js
imports/client/utils/uniforms-custom/DateField.js

equivalent to [PR #920](https://github.com/focallocal/fl-maps/pull/920)

default to open-ended ending date for special category events (fl-sleeper)

---

imports/both/i18n/en/video.json
imports/client/ui/components/VideoPlayer/index.js
imports/client/ui/components/VideoPlayer/styles.scss
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss
imports/client/ui/style.scss
package.json

Equivalent to [PR #922 to master](https://github.com/focallocal/fl-maps/pull/922/)

 Included video player in page heading (fl-sleeper)

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/ui/pages/NewEvent/FormWizard/VideoLink/index.js
imports/client/ui/pages/NewEvent/FormWizard/VideoLink/styles.scss
imports/client/ui/pages/NewEvent/styles.scss
imports/client/utils/uniforms-custom/SelectField.js

Equivalent to [PR #933 on master](https://github.com/focallocal/fl-maps/pull/933)

 Multiple fixes/formatting tweaks to video links submission (fl-sleeper)

---

imports/client/ui/app.js
imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/pages/About/index.js
imports/client/ui/pages/Faq/Content.js
imports/client/ui/pages/WhitePaper/index.js

Equivalent to [PR #935 on master](https://github.com/focallocal/fl-maps/pull/935).
NOTE: Also added blank whitepaper placeholder component; this was an extra route in master's app.js (adding the placeholder means that now app.js is the same across both master and sleeper, so future code changes will be easier to duplicate across the branches)

DCS Balloons/Docus sidebar icons can now be added anywhere on site (fl-sleeper)

---

imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/pages/Faq/Content.js

Equivalent to [PR #937 on master](https://github.com/focallocal/fl-maps/pull/937)

 Enable multiple balloons of the same type (fl-sleeper)

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/utils/Gravatar.js

Reverts focallocal/fl-maps#939

Revert "Ux/ui button redesign to increase click through"

---

imports/client/ui/app.js
imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/components/DCSBalloon/style.scss
imports/client/ui/pages/Faq/Content.js
imports/client/ui/pages/Faq/index.js
imports/client/ui/pages/WhitePaper/index.js

Equivalent to [PR #941 on master](https://github.com/focallocal/fl-maps/pull/941)

 Balloons now display created forum topics for their respective landing page (fl-sleeper)

---

imports/client/ui/components/VideoPlayer/index.js
imports/client/ui/components/VideoPlayer/styles.scss

Equivalent to [PR #943 on master](https://github.com/focallocal/fl-maps/pull/943)

update subscribe button with div overlay that reads 'Subscribe' (fl-sleeper)

---

imports/client/ui/pages/Map/index.js
server/methods/events/getEvents.js
server/methods/events/getFutureEvents.js

Equivalent to [PR #945 on master](https://github.com/focallocal/fl-maps/pull/945)

 Update map to display all visible events on zoom out (fl-sleeper)

---

imports/client/ui/pages/WhitePaper/index.js
imports/client/ui/pages/WhitePaper/styles.scss

Various formatting fixes to whitepaper page

Formatting fixes to whitepaper (master)

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Map/index.js
imports/client/ui/pages/Page/index.js

Close page button redirects user to the map with the current user location or the one they entered on the main page and the list of local events.

Close page button

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Map/EventsList/EventsListItem/index.js
imports/client/ui/pages/Map/EventsList/index.js
imports/client/utils/Gravatar.js

- if special category selected, display gravatar of event organiser n events list and selected event info
- resize "more" button in event info

fl-sleeper gravatar

---

imports/client/ui/pages/NewEvent/FormWizard/FirstStep.js

Move event name above event intro

---

imports/client/ui/app.js

equivalent to[ PR #967 ](https://github.com/focallocal/fl-maps/pull/967)

Implement routing from discourse to whitepaper page (sleeper)

---

imports/both/i18n/en/video.json
imports/client/ui/components/VideoPlayer/Subscribe.js
imports/client/ui/components/VideoPlayer/index.js
package.json

Equivalent to PR [#971 on master](https://github.com/focallocal/fl-maps/pull/971)
BUT - did not touch i18n as my understanding is that is where all the difference is between master/sleeper? So in this PR I'm just updating the Video Player and Subscribe Btn (with JSDOCs and link to new YT channel).

 Revised Video Player with new channel details (sleeper)

---

imports/client/ui/pages/Page/style.scss

Relates to [PR #975 on master](https://github.com/focallocal/fl-maps/pull/975)

Enable line-break rendering (sleeper)

---

imports/client/ui/components/VideoPlayer/index.js

Some old events in the database have category names that no longer exist in i18n. This would throw an Error when the video player tries to match the category with a playlist.
Example: https://focallocal.org/page/fQofMSMmQu3p6H47n would crash upon loading (category name was: "Meet Me and Take #PublicHappiness to the Streets").
Solution: added a check in the video player such that if it's not able to find anything in i18n 'categories.json' that matches the category saved in the database, it will default to 'play any random video' and avoid crashing. (note: after the fix, once the event can load again on the website, you should then be able to edit and change the category to something that does exist if you don't want it to default to 'any random video')

Fix page crash for events with legacy categories that no longer exist (master)

---

imports/client/ui/components/VideoPlayer/index.js

Equivalent to [PR 977 on master](https://github.com/focallocal/fl-maps/pull/977)

Fix page crash for events with legacy categories that no longer exist (sleeper)

---

imports/client/ui/pages/Page/index.js

I thought being explicit with the name would be good so the user knows exactly what it does. I put it Under the video on the left hand side so it is more like a back button.

Back to map btn

---

imports/client/ui/pages/Map/EventsList/MinimizeButton/index.js
imports/client/ui/pages/Map/EventsList/index.js
imports/client/ui/pages/Map/mobile-styles.scss

Equivalent to [PR#984 on master](https://github.com/focallocal/fl-maps/pull/984)

Allow users to hide map filter window on mobile screen (sleeper)

---

imports/client/ui/app.js
imports/client/ui/pages/Errors/index.js
imports/client/ui/pages/Errors/styles.scss

Equivalent to [PR #989 on master](https://github.com/focallocal/fl-maps/pull/989)

Configured router to a new 404 page for non-listed URL paths (sleeper)

---

imports/client/ui/app.js

Equivalent to [PR #992 on master](https://github.com/focallocal/fl-maps/pull/992)

Bugfix - 404 page triggered by some valid paths that were not part of main router (sleeper)

---

imports/client/ui/pages/Page/index.js

Same as [PR #1000 on master](https://github.com/focallocal/fl-maps/pull/1000)

Remove Coral Talk from Pages file (and cleaned up Pages imports for better readability) (sleeper)

---

imports/client/ui/pages/Map/EventsFilter/index.js
imports/client/ui/pages/Map/EventsFilter/styles.scss

More visible (darker grey), bigger (1.5em) but the positioning is not perfect due to the absolute position.

Makeiconbigger

---

imports/client/ui/pages/Home/FirstSection/Find/index.js
imports/client/ui/pages/Home/FirstSection/index.js

Small fixes for the V2 site when there is no navbar

V2 Site: fixed new event button and bound enter key to execute location search

---

imports/both/i18n/en/team.json
imports/client/ui/pages/TeamMembers/Members.js
imports/client/ui/pages/TeamMembers/index.js
imports/client/ui/pages/TeamMembers/team.scss
imports/client/ui/pages/WhitePaper/index.js
package-lock.json

Also included some anchor links at the top to navigate the teams in case it gets too "busy".
A couple of example shots:

Revised team page to include multiple sections. Pending final team data (master)

---

imports/both/i18n/en/whitepaper/why.json
imports/client/ui/pages/WhitePaper/Why/Content.js
imports/client/ui/pages/WhitePaper/styles.scss

1) split the json file into two sections
2) added a second array map to the react element so it renders the second section
3) some small tweaks to the mobile layout as previous layout was causing a jarring horizontal scroll due to excessive margins

Fixed whitepaper "why" bullet point rendering and mobile layout (master)

---

imports/both/i18n/en/btm/team.json
imports/both/i18n/en/phm/team.json

Adding my information to the team page finally :)

add info to team page

---

imports/client/ui/components/__tests__/HoursFormatted.test.js
imports/client/ui/pages/Map/EventsList/MinimizeButton/index.js
imports/client/ui/pages/Map/__tests__/MinimizeButton.test.js
imports/client/ui/pages/Map/__tests__/SearchButtons.test.js
imports/client/ui/pages/NewEvent/__tests__/Recurring-Monthly.test.js

I was able to fix some test that was fail to pass. I am not sure error abour Meteor is not defined almost all the test suites.I try to reinstall npm if will help install Meteor. No go. I will continue to research on this issue.

Unit testing branch

---

imports/client/ui/pages/Page/style.scss

https://publichappinessmovement.com/t/topic/1585

Removed title max height & overflow and resize it on mobile

---

imports/client/ui/components/HoursFormatted/index.js

[same as this PR](https://github.com/focallocal/fl-maps/pull/1042) but on the correct phm branch

Handle empty endingDate (phm)

---

imports/client/ui/components/HoursFormatted/index.js

[same as this PR](https://github.com/focallocal/fl-maps/pull/1042) but on the correct btm branch

Handle empty endingDate (btm)

---

deployment/brightertomorrowmap/mup-secrets.enc.json
deployment/publichappinessmovement/mup-secrets.enc.json

The Atlas/mLab migration is complete and the Mongo connection strings need to be updated here. 
https://publichappinessmovement.com/t/topic/2043/9

Update Atlas mongo connect strings

---

.meteor/versions
package.json

Dusting off some cobwebs to look at upgrading a few core versions.

Version housekeeping

---

imports/both/i18n/en/phm/home.json

Reverts focallocal/fl-maps#1119

Revert "Adding stats"

---

deployment/publichappinessmovement/mup.js

Use node 12 base to fix deploy errors.

Use node 12 base

---

.travis.yml
deployment/publichappinessmovement/mup.js

Use node 12 in builds

---

imports/both/i18n/en/index.js
imports/both/i18n/en/phm/map.json
imports/client/ui/pages/Map/EventsList/EventInfo/index.js

- Updates event details buttons found in the map from 'More' to 'Open' 
- Updates to use i18n
- Includes 'Meteor' in a file where it was throwing an error

Update open event details buttons to use i18n

---

imports/both/i18n/en/phm/map.json
imports/client/ui/pages/Page/index.js

Hey, New pull-request with the need changes only. :)

Adding Share-Your-Experience header to i18n file

---

.travis.yml
deployment/brightertomorrowmap/mup.js
deployment/publichappinessmovement/mup.js
deployment/testing/mup.js

Meteor node 12 base

---

deployment/publichappinessmovement/mup.js

Reverts focallocal/fl-maps#1168

Revert "Testing a url change to find the secrets file"

---

client/main.html
client/main.js
imports/client/ui/includes/MainMenu/DropDownItem/index.js
imports/client/ui/includes/MainMenu/LinkItem/index.js
imports/client/ui/includes/MainMenu/Sidebar/index.js
imports/client/ui/includes/MainMenu/Sidebar/styles.scss
imports/client/ui/includes/MainMenu/UserItem/index.js
imports/client/ui/includes/MainMenu/index.js
imports/client/ui/includes/MainMenu/styles.scss
package-lock.json
package.json

Updated to use `fontawesome` version 6 
Setup with React by using `react-fontawesome` component 
This PR fixed the menu bar and side bar icons. All the other ones will be updated with future PRs.

Update fontawesome - menu and side bar icons

---

imports/client/ui/pages/Home/EventsSection/Item/index.js
imports/client/ui/pages/Home/MovementSection/Item/index.js
imports/client/ui/pages/Home/ProjectsSection/Item/index.js

&nbsp; aka Non-Breaking Space character was the culprit. Removed and closed span tags.

Remove random lines under item links within section cards

---

imports/client/ui/pages/Map/EventsFilter/index.js
imports/client/ui/pages/Map/EventsFilter/styles.scss
imports/client/ui/pages/Map/EventsList/EventsListItem/styles.scss

Inside categories-item marginLeft changed to paddingLeft so there is no blank space.
Commented box shadow to remove the shadow background under not filled filter items.
Added style for .form-check-label to justify text alignment for inherited filter items.
Changed max-height inside event-list-item to fit the content inside the box.

Content alignment changes for the sidebar

---

imports/both/i18n/en/phm/whitepaper/intro.json
imports/client/ui/pages/WhitePaper/Intro/TopImageSection/style.scss
imports/client/ui/pages/WhitePaper/Intro/style.scss

- Adjusted padding and margins for mobile views in Intro section
- Enhanced TopImageSection styling with responsive image sizing
- Improved mobile layout for top image with max-width and max-height constraints

Update WhitePaper Intro responsive styles for mobile layout
