package.json

@AndyatFocallocal There was an accidental comma in package.json. That was causing an error in the building process. It should work now.

Removed comma causing error

---

both/i18n/en/app.en.i18n.json

Just noticed a couple words spelled incorrectly - "positivity" and "below."  Apologies if this is too small an issue to warrant a pull request, but I figured I'd help any way I could!

Minor spelling errors

---

imports/client/ui/pages/Page/index.js
package.json

Functioning comment system without any third party oAuth, sign in is done through built in Coral Talk. In order to function you [must setup server](https://docs.coralproject.net/talk/) until we have system setup on host server. Pages function properly with or without the server operational, comments just don't show if not setup. If we don't pull into master, this branch can still be used by everyone to make adjustments.

Comment system only Coral login, no oAuth yet

---

imports/client/ui/pages/Page/index.js

Updated the script tag to reflect the url with https. Only way to confirm this is working is to give the URL time to update with new IP for talk.focallocal.org and then see if the live site actually shows the script.

Commenting updated to HTTPS, needs confirmed once live

---

imports/client/ui/app.js
imports/client/ui/pages/NewEvent/FormWizard/index.js
imports/client/ui/pages/NewEvent/index.js

This is my first ever pull request and more of a temporary patch.
Before modal closes, unfinished form is copied to a window obj for later retrieval. 
Unfinished form data is deleted after resetting or submitting a completed form, and between different route changes.
I also commented out a line that told the modal to redirect the user to /home every time it closed. It should now close back to where it was opened from.

saved unfinished New Event form to window obj before closing modal for later use in FormWizard

---

imports/client/ui/pages/Map/EventsList/EventInfo/index.js
imports/client/ui/pages/Page/AttendingButton/index.js
imports/client/ui/pages/Page/index.js

Removed the attend button from the UI (left 1 liner comment in case we need to add back in future). [relates to this issue on trello](https://trello.com/c/qfwPJzYU/488-both-delete-the-attend-button-not-in-the-page-only-in-the-preview)
Below are some screenshots of the revised look without the button.

Remove Attend button (both on EventInfo and Event Page)

---

imports/client/utils/uniforms-custom/AutoForm.js

Fixes #771. This was not a current key task on Trello, sorry if that's an issue.
What I've done in this PR is check if `when.startingDate > when.endingDate` and if so adjusting the one that was not changed to match the new choice. 
Note that the starting and ending clock times can still be inconsistent if startingDate and endingDate are the same.

override AutoForm onChange method to handle dates

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

Relates to [issue #879](https://github.com/focallocal/fl-maps/issues/879)
**Solution:** add default value to the weekday field, which can be overwritten by the user filling out the form.
- update db schema autovalue: if recurring type is 'week', but weekday has not been set by the user, it will revert to the weekday of the event's start date.
- update react component: pass the autovalue to the weekday UI component so that the user sees the default weekday highlighted on the form itself, as per the screenshot below (start date 27th Feb => Wednesday). User can then replace the default/add further days to the default as needed.
Any questions let me know.

update schema+UI: default repeating weekday set to start date's weekday

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

Reverts focallocal/fl-maps#896
travis failed, although the PR was good. reverting so it can be made again, there is an intermittent bug in travis that seems to fail around 1 in 4 PR's

Revert "update schema+UI: default repeating weekday set to start date's weekday"

---

imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/components/HoursFormatted/styles.scss
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/Monthly/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js
imports/client/utils/findNextEvent.js

**Changes:**
1 - Should finally resolve the [creating weekly events without selecting a weekday bug](https://trello.com/c/VXmZkc08/494-bug-user-can-post-event-recurring-every-week-ignoring-day-of-the-week-field-subsequent-event-page-causes-crash). I had to change approach slightly: previously had implemented a 'default weekday' auto-selected, but this was causing problems with the buttons, and also the user could still deselect and submit a blank form. Now there is no default, however the field is required and the user will get an error message instead (screenshot 1).
2 - date/time module has been redesigned as parts were incomplete. If an event is repeating, the box will display when is the next event from today, followed at the bottom by a description of the schedule and end date where …

Events recurrence - complete timeDate module and repair recurrence selection

---

imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/pages/NewEvent/FormWizard/DateTimeModule/Recurring/index.js

**Main fix**: [this issue when trying to change event from one-time to recurring](https://trello.com/c/Xmi9uZV2/491-bug-attempting-to-edit-event-to-recur-breaks-the-app). (the problem was that when you submit a form for a one time event, it saves the 'recurring' field as null in the db, which threw an error when the subsequent edit tries to attach data onto the null object).
=> Added a conditional to replace null object with empty object when changing the event to recur.
**Additional small fix**: noticed that the form also allows you to leave both 'number of repeats', and 'until' fields blank when you are asked to provide an end date to a recurring, not-forever event (so you end up with a blank end date). On the other hand, it also lets you enter data in _both_ and submit (so you have …

Bugfix: Attempting to edit event to recur breaks the app (master)

---

README.md

Instructions on how to copy changes from master to sleeper with a simple command in the terminal.
(I added it in the workflow section, let me know if you prefer it elsewhere)
fyi - I noticed the readme in master is significantly different from sleeper. Looks like master has more detail in there so I've only modified that one (difference between master and sleeper in the txt file)
[gitDiff.txt](https://github.com/focallocal/fl-maps/files/2922910/gitDiff.txt)

updated README.md with cherry-pick instructions

---

imports/both/collections/events/helpers/index.js
imports/both/collections/events/index.js
imports/client/ui/components/HoursFormatted/index.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/utils/format.js
imports/client/utils/uniforms-custom/DateField.js

relates to [this issue](https://trello.com/c/zQDzkGbT/505-create-always-button-on-time-date-modal-and-set-the-special-category-to-default-to-it) 
Fix ended up being more fiddly than I expected because of how the form, database and React interact with one another... Let me know if any of the below doesn't make sense/you prefer a different solution. As mentioned below I decided to have the calendar input itself double up as the "always" button instead of having an extra button as suggested in the trello task, because adding a new one was breaking the formatting for the rest of the boxes/columns.
**User summary:**
- When user selects meet me for action/community offers, the end date calendar will display the info message 'Leave blank for Always' (screenshot 1)
- Leaving it untouched will …

default to open-ended ending date for special category events (master)

---

imports/both/i18n/en/video.json
imports/client/ui/components/VideoPlayer/index.js
imports/client/ui/components/VideoPlayer/styles.scss
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss
imports/client/ui/style.scss
package.json

Added video player and made some visual adjustments to insert into the page header. Relates to [this issue on Trello](https://trello.com/c/udFhd40S/412-both-video-player-in-pages-header-section) however the link upload form functionality is still WIP
- Videos are chosen from the i18n file video.json, selected randomly from within individual playlists if playlists are matched with the event category on display, or from the entire selection of videos if there is no match found (e.g. free hugs will only play free hugs videos, but 'meet me for action' will pick a video from the entire focallocal channel at random)
- Once the video ends, a new random video will start. Youtube doesn't allow this natively, so I made it so the React component re-renders itself once a video ends.
Additional small …

Included video player in page heading (master)

---

imports/both/collections/events/index.js
imports/client/ui/pages/NewEvent/FormWizard/SecondStep.js
imports/client/ui/pages/NewEvent/FormWizard/VideoLink/index.js
imports/client/ui/pages/NewEvent/FormWizard/VideoLink/styles.scss
imports/client/ui/pages/NewEvent/styles.scss
imports/client/utils/uniforms-custom/SelectField.js

Managed to incorporate the bulk of the changes we discussed, in one way or another:
1 - **Difficulty scrolling down list of video hosts when having to click via a desktop mouse.**
This one was a bit harder than I had anticipated: the scrollbar does not appear because the react form prefers to expand the entire modal rather than add a scrollbar to the submenu. **Workaround**: I've moved the video links section to the very end of the form (below attendee limit), and made it so that the menu opens up UP instead of DOWN. That way you will always have enough room on the screen to see every choice (except for smaller mobiles, but they can thumb-scroll I guess)
2 - **Moving buttons to below the links** done
3 - **Error in video links submission sometimes propagates to description input box** …

Multiple fixes/formatting tweaks to video links submission (master)

---

imports/client/ui/app.js
imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/pages/About/index.js
imports/client/ui/pages/Faq/Content.js

Relates to [this issue](https://trello.com/c/zvu6y3GJ/550-team-challenge-docus-sidebar-icons-can-be-added-anywhere-in-the-site)
**Note** in order to minimize code repetition, I've updated how the balloons are rendered in other parts of the site .
_Before_: rendered via a function that needs to be defined within the same component where you want to add the balloon, and which depends on a handful of other functions, some of which were also being defined locally and some passed down as component props from app.js:
`{this.dcsHeading(title, subtitle, balloonCode)}`
_After_: the DCS balloon is now its own React component with most of the logic defined internally (so it can be added anywhere on the site without having to include additional functions/logic). On the page you want to add a baloon …

DCS Balloons/Docus sidebar icons can now be added anywhere on site (master)

---

imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/pages/Faq/Content.js

BEFORE: Each DCSBalloon was identified by its code (e.g. 'pho' = photos), all balloons on the same page of the same type lead to the same landing site on the forum (e.g. all photo balloons on a particular page lead to the same landing site)
AFTER: you can now add a numeric multiplier to the balloon code (e.g. 'pho123'), this will modify the landing page accordingly. The balloon's icon will be the same across all of the same type (e.g. same icon for pho1 and pho5)
NOTE: adding a non-numeric character to the balloon code (e.g. 'phoxyz') will throw an error.

Enable multiple balloons of the same type (master)

---

imports/client/ui/app.js
imports/client/ui/components/DCSBalloon/index.js
imports/client/ui/components/DCSBalloon/style.scss
imports/client/ui/pages/Faq/Content.js
imports/client/ui/pages/Faq/index.js
imports/client/ui/pages/WhitePaper/index.js

Balloon component now takes an additional prop (dcsTags) which is data passed from docuss via app.js. Consequently app.js has been refactored to pass dcsTags to its children.. but if you need to add a balloon to it's 'grandchildren', you would need to refactor accordingly to pass dcsTags onto them as a prop then onto DCSBalloon. Have done this for the whitepaper page, and the first page of the FAQ.
Placeholder example added to whitepaper page (Screenshot):
- first balloon points to code 'bal' which has 1 topic posted in the forum
- second and third balloons point to 'bal1' and 'bal2' respectively, will update once topics are posted onto their landing pages

Balloons now display created forum topics for their respective landing page (master)

---

imports/client/ui/pages/Map/index.js
server/methods/events/getEvents.js
server/methods/events/getFutureEvents.js

Relates to [this issue on Trello](https://trello.com/c/I8EyfawY/437-both-key-task-urgent-pins-arent-showing-on-the-map-at-all-except-for-the-area-you-search), or [this on GitHub](https://github.com/focallocal/fl-maps/issues/820)
Problem: getEvents methods were set to return events limited to 100km from centre of google map
Resolution: will now return events within 100km, OR within the visible screen radius (whichever is greater).

Update map to display all visible events on zoom out (master)

---

.meteor/packages
.meteor/versions
imports/both/i18n/en/menu.json
imports/client/ui/app.js
imports/client/ui/includes/MainMenu/UserItem/index.js
imports/client/ui/includes/MainMenu/index.js
imports/client/ui/pages/Admin/AdminTable/index.js
imports/client/ui/pages/Admin/RoleSelect/index.js
imports/client/ui/pages/Admin/RolesPermissions/index.js
imports/client/ui/pages/Admin/index.js
imports/client/ui/pages/NewEvent/index.js
imports/client/ui/pages/Page/index.js
imports/client/utils/adminControl.js
server/methods/admin/addRole.js
server/methods/admin/changeRole.js
server/methods/admin/checkPermissions.js
server/methods/admin/deleteUser.js
server/methods/admin/getEvents.js
server/methods/admin/getUsers.js
server/methods/admin/index.js
server/methods/events/deleteEvent.js
server/methods/events/editEvent.js
server/methods/index.js

Straight forward admin page. Admins can change user roles or delete them. Also, includes links to user posts so that moderators or admins can edit/delete the posts. There is a file that you will want to look at. imports\client\ui\pages\Admin\RolesPermissions\index.js because here you will see how the permissions are set. 
`export const roleOptions = ["admin", "moderator", "user"]
export const permissions = {
adminPage: ["admin", "moderator"],
changeRole: ["admin"],
deleteUser: ["admin"],
deleteEditResource: ["admin", "moderator"],
}` 
Right now only admins can delete users or change roles while both moderators and admins can delete or edit posts.  When you make a change to the user you will see an entry in the user document under roles.__global_roles__ in the database.
When you want to …

Admin roles page

---

imports/client/ui/app.js

app.js now checks the discourse tag for the whitepaper page and adjusts history accordingly, so you don't get an undefined meteor page when you click on a topic link

Implement routing from discourse to whitepaper page (master)

---

imports/client/ui/components/DCSBalloon/index.js

Previously post count was looked up by using balloon id as _prefix_ which caused errors where multiple balloons had the same prefix. Switched to looking up the balloon id exactly as is (so far works as expected on whitepaper page based on a few tests).

Fix balloon tag forum post count (master)

---

imports/both/collections/events/index.js
imports/both/i18n/en/categories.json
imports/client/ui/components/VideoPlayer/index.js
imports/client/ui/pages/Map/EventsFilter/index.js
imports/client/ui/pages/Map/EventsFilter/styles.scss
imports/client/utils/uniforms-custom/SelectField.js

Equivalent to [PR #973 on master](https://github.com/focallocal/fl-maps/pull/973)
Currently all BTM categories roll up into 1 parent 'Communities Supporting People' but this can be changed or expanded in i18n.

 Enable double-level categories across event form and map filtering (sleeper) 

---

imports/client/ui/pages/Page/style.scss

Relates to [this issue on trello](https://trello.com/c/sKvcvQZh/573-bug-pages-preserve-spaces-paragraphs-line-breaks-etc)
It's a very short/quick css fix once you know about it :)
Copied the text block presented on trello and included a double line break before 'Important Notes' and single line breaks before each numbered list item to test:
**Example before:**
**Example after:
**

Enable line-break rendering (master)

---

imports/both/collections/events/index.js
imports/both/i18n/en/map.json
imports/client/ui/components/SharePanel/index.js
imports/client/ui/components/SharePanel/styles.scss
imports/client/ui/components/VideoPlayer/index.js
imports/client/ui/pages/Page/index.js
imports/client/ui/pages/Page/style.scss
imports/client/utils/uniforms-custom/SelectField.js
package-lock.json
package.json

This is at least a partial solution to [this issue on Trello](https://trello.com/c/Uxv4Ts8N/503-key-task-links-added-to-pages?menu=filter&filter=label:Meteor%20Dev)
Event pages now have share buttons for the main social media + email, on clicking user gets a popup to confirm share, which is pre-populated with link to event page, together with the event title and the date and time of the event (wording can be edited in i18n).

New widgets/buttons to auto-share event details on social media (master)

---

imports/client/ui/pages/Map/EventsList/MinimizeButton/index.js
imports/client/ui/pages/Map/EventsList/index.js
imports/client/ui/pages/Map/mobile-styles.scss

Relates to [this issue on Trello](https://trello.com/c/M8FU8GPB/469-on-mobile-in-portrait-vertical-users-cant-close-the-filters-window-on-main-map-page).
Added a button to minimize/maximize the menu on mobile screens. Same format as in desktop version only the hiding movement happens downwards (instead of leftwards):
Screenshot of minimized menu (with 'maximize' button to re-open menu when needed):

Allow users to hide map filter window on mobile screen (master)

---

imports/client/ui/app.js
imports/client/ui/pages/Errors/index.js
imports/client/ui/pages/Errors/styles.scss

Relates to [this issue on trello](https://trello.com/c/w7wO45sc/282-both-key-task-create-a-404-page-not-found-page).
The page itself is pretty basic, but works around all the other components so shouldn't interfere if you then click on "Gather" to add a new event.

Configured router to a new 404 page for non-listed URL paths (master)

---

imports/client/ui/app.js

Just came across a second nested (hidden) react router that was part of the app's authentication component, with a couple of url paths dedicated to auths, such as '/reset-password' and '/forgot-password'.
As these were not part of the main app logic they were triggering the 404 page so I had to tweak the 404 page router manually.

Bugfix - 404 page triggered by some valid paths that were not part of main router (master)

---

imports/client/ui/pages/Page/index.js

no visible changes; just removed the script tag with Coral talk embedded, and re-organised the list of imports into categories

Remove Coral Talk from Pages file (and cleaned up Pages imports for better readability) (master)

---

imports/both/i18n/en/index.js
imports/both/i18n/en/whitepaper/index.js
imports/client/ui/app.js
imports/client/ui/pages/WhitePaper/Intro/FirstSection/index.js
imports/client/ui/pages/WhitePaper/Intro/SecondSection/index.js
imports/client/ui/pages/WhitePaper/Intro/TopImageSection/index.js
imports/client/ui/pages/WhitePaper/Intro/index.js
imports/client/ui/pages/WhitePaper/Why/Content.js
imports/client/ui/pages/WhitePaper/faqs/Content.js

Changed three areas to be able to display the new pages:
- new pages were added to i18n folder without wiring up the import/export of the data in an index.js file (the fix is in the first two changed files below)
- the new URLs need to be added to the router in app.js (the fix is in the third file change below)
- some small typos dotted about in the whitepaper folder which throw errors when trying to compile (fix is in the remaining file changes below)
NOTE: looks like the content under why/ and faq/ in 18n is currently the same so the pages looks exactly the same - assume it will be updated further down the line?

Attempted repair whitepaper sub-pages

---

imports/both/collections/events/index.js

@AndyatFocallocal  'Event Categories' was hard coded into the schema. I fixed it to be dynamic. However, I am not sure if the brightertomorrow live site is even using the correct code. It does not seem to be using the same code as publichappinesss.  I think it is still using the fl-sleeper  I found this line in the readme  
- *settings.json* has a property named `'mapType': 'gatherings'` ,
you can change 'gatherings' to 'btm' to work on Focallocal or Brighter Tomorrow
When I changed the setting to btm it looked different from the live site. It looked more like publichappiness with correct links instead of bubbles and a btm logo on top left.
Fixing this problem https://publichappinessmovement.com/t/topic/1610/2

Categories placeholder

---

imports/both/i18n/en/phm/home.json

My commenting out doesn't seem to work. 
@Marvelxy I noticed you used a different method which wasn't familiar to me. Would you help me understand why the commenting out doesn't work in this PR please

Adding stats

---

.travis.yml
deployment/brightertomorrowmap/mup.js
deployment/publichappinessmovement/mup.js
deployment/testing/mup.js

I found in the doc to use this version `zodern/meteor:root` for the docker image.
See: https://meteor-up.com/docs.html#meteor-support
I figured it might worth a try to see if it can fix some of the deployment issues?
I don't know if master branch/testing server can actually do deployment though.. but we can't put it in deploy-phm because the app isn't working yet..

Change zodern-meteor version

---

imports/client/ui/pages/Map/EventsFilter/index.js

This is to add back the event filter I've commented out earlier.
screenshot:

Added back event filter on the map
